google/gops

- main.go
On Windows, https://github.com/keybase/go-ps return list of processes contains system process. System process ID is 0. So 
https://github.com/keybase/go-ps/blob/master/process_windows.go#L170-L172
modules always return current process if passing 0. Then gops return below.
```
0       [System Process]        (c:\dev\godev\src\github.com\google\gops\gops.exe)
1188    jvgrep.exe      (c:\dev\godev\src\github.com\mattn\jvgrep\jvgrep.exe)
17872   gops.exe        (c:\dev\godev\src\github.com\google\gops\gops.exe)
```
I'm not sure this is an issue which should be fixed in https://github.com/keybase/go-ps, however gops can ignore system process.
> ignore system process

- agent/agent.go
- cmd.go
- signal/signal.go
This PR adds more Go runtime information such as go routine count, number of CPUs, and GOMAXPROCS.
Closes #5
> Runtime vitals

- agent/agent.go
- cmd.go
Trying to build on the comment:
> I want to move off of the unix socket and want to listen on a TCP socket instead. I am planning to listen on a random port and keep the port process is listening under $HOME/.gops/.addr. This will also enable the windows support.
Not sure about the perms, though.
> #10 replace unix socket by tcp

- agent/agent.go
When I see `last-gc: xxx ns ago`, I think it means time elapsed between last GC and now, but actually it's not, if you think so, please consider merge this PR, or I think deleting `ago` is a little more understandable.^_^
> agent.go: time ago issue

- README.md
- main.go
pprof-mem is invalid command, some of them mixed up with pprof-heap & pprof-cpu in README & flag usage
> fix typo in README and usage

- cmd.go
- signal/signal.go
- a function as a wrapper to cmd if printing is needed.
- a small typo fix in signal package comments
> Some drying in cmd calls

- agent/agent.go
- agent/agent_test.go
- examples/hello/main.go
If the application the agent is being installed on also need to run some shutdown code during an Interrupt signal, it's important to have the ability to prevent gops agent from calling os.Exit(). This also adds the requirement of exposing a method to manually cleanup garbage left by the gops agent.
To allow custom agent flags now and in the future an Agent type was created with a public boolean field HandleSignals. This allowed preserving the current interface by having the Start() method start an Agent with HandleSignals set to true. The Agent type also exposes a Stop() method to perform the necessary cleanup.
This PR also adds some basic initial testing to Agent start and stopping.
> Allow starting the agent without installing a signal handler

- agent/agent.go
Using `pprof.Lookup("goroutine")` instead of `runtime.Stack` directly because the former already takes care of expanding the buffer used with `runtime.Stack` until it's big enough for the stack.
> agent: avoid truncating stack trace if it's bigger than 64kb

- agent/agent.go
- agent/agent_test.go
I'm not sure if this is wanted of not but decided to give it a try, please feel free to dump this if this change isn't wanted. :)
The output from memstats with these changes look like:
```
alloc: 3MB (3283704 bytes)
total-alloc: 7GB (7826209192 bytes)
sys: 8MB (8427768 bytes)
lookups: 7
mallocs: 16170
frees: 15572
heap-alloc: 3MB (3283704 bytes)
heap-sys: 4MB (4784128 bytes)
heap-idle: 1MB (1073152 bytes)
heap-in-use: 3MB (3710976 bytes)
heap-released: 0 bytes
heap-objects: 598
stack-in-use: 448KB (458752 bytes)
stack-sys: 448KB (458752 bytes)
next-gc: when heap-alloc >= 4MB (4194304 bytes)
last-gc: 2017-01-10 16:11:10.912477567 -0200 BRST
gc-pause: 59.760994ms
num-gc: 1865
enable-gc: true
debug-gc: false
```
> agent: prettier formatting for units printed by memstats

- README.md
- agent/agent.go
- cmd.go
- examples/hello/main.go
- main.go
- signal/signal.go
This PR adds a possibility to use this tool for instrumented binaries running on remote hosts.
PR adds new protocol command, which dumps running service's binary file. Two dependencies were added, namely github.com/pkg/errors for errors' contexts and github.com/kardianos/osext, which helps agent find the path to executable file.
Interface changes are simple: it is now possible to pass `host:port` combo instead of `PID` to gops tool.
> Added remote mode support

- cmd.go
Sometimes it's useful to grab profiling files and copy them somewhere else. Having the client print the temp file names used to store these dumps helps with this.
> Print filenames on client for pprof and trace dumps

- agent/agent.go
- agent/agent_test.go
- examples/hello/main.go
Users are having trouble that agent is stealing the notifier
by default. Make the feature more obvious by making it
non-default.
> agent: don't close on interrupt by default

- cmd.go
On our servers we have the go tool chain not installed and the servers are behind a firewall (no tunnels possible).
With this pull request it would be possible to perform a trace or pprof and copy the trace file to a system where I have the go tool chain installed. There I could run `go tool trace <tracefile>` and analyze the trace file with the browser.
This could maybe also solve #44.
If the go tool chain is not available you get the following output:
```bash
$ gops pprof-heap localhost:41081            
Profile dump saved to: /tmp/profile936731714     
$ gops pprof-cpu localhost:41081                                                                                                   
Profiling CPU now, will take 30 secs...   
Profile dump saved to: /tmp/profile262095472    
$ gops trace …
```
> Keep trace and profile files when go tool chain is not available

- README.md
In the README the basic example show that a `nil` value can be passed to `agent.Listen`. This results in a compile error. 
This change is a simple change in the README to rather pass an empty `agent.Option`
> replace nil parm with empty Options

- main.go
I can't seem to remember the order in which the command and target goes. Probably a gops-newbie syndrome. So I think having the order spelled out in the help usage text helps.
> Add usage synopsis in help message

- cmd.go
- instead of strings.Index check
> cmd: Use strings.Contains

- goprocess/gp.go
- goprocess/gp_test.go
There's a data race inside `gops/goprocess.FindAll` where the `results` list is written to in parallel. 
I introduced a goroutine which collects the results and writes to the `results` list in a thread safe manner.
> Fixed data race in "FindAll" function. 

- Gopkg.lock
- main.go
- vendor/github.com/xlab/treeprint/struct.go
- vendor/github.com/xlab/treeprint/treeprint.go
- vendor/github.com/xlab/treeprint/treeprint_test.go
Hi, in our internal testing tool we found that a PR of xlab/treeprint (https://github.com/xlab/treeprint/pull/6) which was merged might break gops in the future. The PR removed treeprint.EdgeTypeStart. To set the root node, we can now use SetValue(value Value) instead.
In this commit,
dep ensure -update github.com/xlab/treeprint
was executed to update the library and then fix is applied.
> address breaking changes from xlab/treeprint

- cmd.go
Before this change, error returned by internal.GetPort was
assigned to err variable, but this assignment was ineffectual
and error was ignored.
> cmd: Check error returned by GetPort

- main.go
Avoid using tabs, remove help from "subcommands" list,
don't differentiate the profiling commands from others.
> Improve the help text

- internal/internal.go
Just as [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) specifies:
>  `$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used. 
\*nix users should be able to use that, before needing to set `GOPS_CONFIG_DIR`
> Check $XDG_CONFIG_HOME before falling to ~/.config

- cmd.go
The path to the profile dump is already logged after writing the file
(cmd.go line 121). Remove the duplicate log line.
> Don't log path to profile dump twice

- agent/agent.go
As part of agent.Close, Close is called on the listener. This has
Accept return a "use of closed network connection" error, which is
expected. This error is logged but it would be nice if it wasn't.
Unfortunately, there's not a great way to check for this
error (https://golang.org/issues/4373) so use a best-effort
strings.Contains check.
> agent: silence error on listener close

- cmd.go
When getting profile dumps for further processing, it's hard to distinguish
CPU and heap profiles from the file names alone. Make this easier by
adding a prefix (cpu or heap) to the file name depending on the type of
profile.
> Add prefix to profile dump file names

- internal/internal.go
- internal/internal_go1_13.go
- internal/internal_lt_go1_13.go
On Go ≥ 1.13 the os package has os.ConfigDir
(https://golang.org/pkg/os/#UserConfigDir) which returns the default
root directory to use for user-specific configuration data. Use this in
internal.ConfigDir if available, while still making sure that any
directory specified in GOPS_CONFIG_DIR takes precedence.
> Use os.UserConfigDir for internal.ConfigDir if available

- agent/agent.go
- go.mod
It's superceded by the standard os package in go 1.8+.
> Remove dependency on kardianos/osext

- agent/agent.go
In func handle, check the error return values of pprof.WriteHeapProfile
and trace.Start.
> agent: check error return values

- internal/internal.go
- internal/internal_test.go
Use a subdirectory of the directory returned by os.UserConfigDir instead
of the UserConfigDir directly. This was missed in #103. Also add a test.
Based on a change by @42wim submitted in #107
> internal: add gops subdirectory in ConfigDir

- internal/internal.go
Use filepath.Join to create a path with correct path delimiters on
Windows.
Based on a change by @42wim submitted in #107
> internal: use filepath.Join in PIDFile

- agent/agent.go
Report PauseEnd, NumForcedGC and GCCPUFraction from runtime.Memstats.
> agent: report additional runtime.MemStats fields

- goprocess/gp.go
- goprocess/gp_test.go
`go version go1.14.6 darwin/amd64`
https://github.com/google/gops/blob/983b7ba5c9fcb398bb823ef0a94889463099457f/goprocess/gp.go#L106
**goversion.ReadExe** will return EMFILE error because of no concurrency goroutines limit in:
https://github.com/google/gops/blob/983b7ba5c9fcb398bb823ef0a94889463099457f/goprocess/gp.go#L29
this error will make some Go processes unrecognized, this PR just add a concurrency limit to solve this problem
> fix: EMFILE error on macOS Catalina

- goprocess/gp.go
Limit the number of concurrent workers by starting a fixed number of goroutines and providing work by an input channel.
Fixes #123
> Fix the worker concurrency model

- main.go
- main_test.go
In case a process has been running for a multiple of 24 hours, the
process runtime will be formatted as DD-MM:SS instead of DD-HH:MM:SS.
Fix this and add a test for `fmtEtimeDuration`.
Also switch from `bytes.Buffer` to `strings.Builder` in `fmtEtimeDuration`.
> Fix formatting for multiple of 24 hours

- agent/agent.go
- agent/agent_test.go
- agent/sockopt_unix.go
- agent/sockopt_unsupported.go
- go.mod
- go.sum
Introduce `Option.SocketReuseAddrAndPort` which, if set, will lead to the
`SO_REUSEPORT` socket option being set on the listening socket on
Unix-like OSes. This also sets `SO_REUSEADDR` which is already the default
in `net.Listen` (see `net.setDefaultSockopts`).
Setting these options increases the chance to re-`bind()` to the same
address and port upon agent restart if `Options.Addr` is set.
> agent: allow to set SO_REUSEPORT on listening socket

- .github/workflows/test.yml
This extends the testing currently done in CircleCI:
* run CI on macOS in addition to Linux and Windows
* testing with multiple Go versions (1.12 through 1.16), not just Go
1.12 like CircleCI
* checks that the code is properly `gofmt`'ed
* checks proper module vendoring
> Add GitHub action for CI testing

- agent/agent.go
If `gopsdir` contains a trailing slash, the resulting `portfile` path will
contain a trailing double slash which might lead to problems in some
circumstances. Moreover iut could also be problematic on platforms where
other path separators are used (e.g. Windows).
Fix this by using `filepath.Join` to construct the path.
> agent: use filepath.Join to construct portfile path

- agent/agent.go
The godoc comment mentions SO_REUSEADDR twice, fix this.
> agent: mention SO_REUSEPORT in Options.ReuseSocketAddrAndPort godoc

- README.md
- main.go
Two followups for #143:
```
Restore CPU usage report format
Commit 78435f89 changed the existing output format for the CPU usage
from `cpu usage:` to `cpu usage (all):`.
This might break existing scripts relying on this format. Revert that
part of the change and only report the CPU usage for the given period
with a suffix:
cpu usage:      0.087%
cpu usage (1s): 1.42%
```
and
```
Allow to specify CPU usage period as duration string
The current implementation assumes the given duration in seconds.
Instead, also allow to specify a duration in the format as expected by
`time.ParseDuration` and use that if found. If a plain integer is
specified, it is still parsed as a duration in seconds.
```
> Fix CPU usage reporting

- README.md
Using `go get -u github.com/google/gops` fails to install gops when
using Go modules. Update the installation instructions accordingly.
For #147
> README.md: update installation instructions

- main.go
Fixes: #154 
Validate `processInfo` period & log a fatal error in the case of negative duration.
Now gops exits and returns a fatal error in the case when the user supplies a negative duration to `gops <pid> <duration>` instead of defaulting to 0 as shown below.
Previously:
```
$ gops 21794 -1.3s
parent PID:     21703
threads:        7
memory usage:   0.040%
cpu usage:      0.000%
username:       admin
cmd+args:       /tmp/go-build3005809368/b001/exe/main
elapsed time:   15:39
local/remote:   127.0.0.1:38793 <-> 0.0.0.0:0 (LISTEN)
```
Now:
```
$ go build && ./gops 21794 -1s  
2021/11/10 18:18:26 Cannot process with negative duration: -1s
```
Note:
In an attempt to validate the duration values, I skipped over validating floats as internally they get converted to the appropriate duration. …
> Error out when the given duration is negative

- .github/workflows/test.yml
- go.mod
This will allow to update github.com/shirou/gopsutil which requires at
least Go 1.13.
> Bump minimum Go version to 1.13

- main.go
Otherwise the processes might appear in arbitrary order and
disassociated from their parent process. Also avoid printing a stray
newline after the tree.
Before:
```
...
├── 2493
│   └── 4952 (gops) {go1.18.1}
├── 1
│   └── 117 (com.docker.vmnetd) {go1.17.5}
├── 4405
│   └── 4416 (gopls) {go1.18.2}
└── 4404
```
After:
```
...
├── 1
│   └── 117 (com.docker.vmnetd) {go1.17.5}
├── 2493
│   └── 4945 (gops) {go1.18.3}
└── 4404
└── 4405 (gopls) {go1.18.2}
└── 4416 (gopls) {go1.18.2}
```
> Sort tree output by PPID

- go.mod
- go.sum
dependabot updated gopsutil to v3.22.11 in PR #189. That tag is no longer available upstream and was retracted, see shirou/gopsutil#1386. Switch back to the previous version for now and let dependabot update once there is a new version.
Fixes #191
> go.mod: downgrade github.com/shirou/gopsutil to v3.22.10

- internal/internal.go
os.UserConfigDir will already check the AppData environment variable on
Windows (environment variable names are case-insensitive on Windows):
https://cs.opensource.google/go/go/+/release-branch.go1.19:src/os/file.go;l=461-465
and the XDG_CONFIG_HOME environment variable on Unix operating systems:
https://cs.opensource.google/go/go/+/release-branch.go1.19:src/os/file.go;l=481-489
> internal: remove redundant environment variable checks in ConfigDir

- README.md
- internal/cmd/shared.go
To stop GC completely, debug.SetGCPercentage needs to receive a negative integer. Passing a negative integer is cumbersome: $ gops setgc <pid> -- -1
This commit adds a more user-friendly way to achieve that: $ gops setgc <pid> off
This behavior is aligned with that of the GOGC env variable, where negative or "off" can be set to stop the GC.
fixes #200
> cmd/shared: add 'off' option to setgc

- agent/agent.go
- goprocess/goprocess_test.go
- internal/cmd/shared.go
- internal/internal.go
package io/ioutil was deprecated as of go1.16 and its functions now directly call io and os functions. It is recommended to use these implementations in new code.
> replace io/ioutil usages with io and os

- internal/cmd/process.go
Use cobra.MinimumNArgs to require at least one argument and handle errors in processing the arguments. Improve the use help string.
> Fix process command crash when provided with no args

- agent/agent.go
In k8s environments one can have read-only file system or no home directory at all (distroless env),
so don't fail start as we have remote listener anyway.
> don't fail if can't save config due to EROFS or EPERM

- agent/agent.go
After #213 the portfile might no longer be written, thus check the listener to determine whether the agent is already listening.
> agent: check listener instead of portfile in Listen

- agent/agent.go
- goprocess/goprocess.go
Named returns should only be used with naked returns, or a deferred function. And in general are better avoided
> Remove some named returns

- agent/agent.go
Rather than duplicating the check in saveConfig, check for EROFS or EPERM on the error returned by saveConfig.
> agent: move check for EROFS/EPERM outside of saveConfig

- .github/workflows/test.yml
- go.mod
Bump the minimum supported Go version to 1.18 in go.mod. Also make sure CI is testing against the latest two versions supported upstream, currently 1.21 and 1.22.
> Bump minimum Go version to 1.18, test on latest supported releases
